### ISSUE TITLE
geolite_original.csv does not exist

### ISSUE THREAD

**Issue by rmccarth** [cmunetcoms20/datascience#17]
stack trace:
```bash
app_1    | Traceback (most recent call last):
app_1    |   File "./driver.py", line 72, in <module>
app_1    |     main()
app_1    |   File "./driver.py", line 31, in main
app_1    |     setup_directories(input_path, output_path)
app_1    |   File "./driver.py", line 51, in setup_directories
app_1    |     ASN.creating_lookups.create_geolite_lookup(input_path, output_path)
app_1    |   File "/ASN/creating_lookups.py", line 40, in create_geolite_lookup
app_1    |     geo_df = pd.read_csv(geolite_input_file)
app_1    |   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 676, in parser_f
app_1    |     return _read(filepath_or_buffer, kwds)
app_1    |   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 448, in _read
app_1    |     parser = TextFileReader(fp_or_buf, **kwds)
app_1    |   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 880, in __init__
app_1    |     self._make_engine(self.engine)
app_1    |   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1114, in _make_engine
app_1    |     self._engine = CParserWrapper(self.f, **self.options)
app_1    |   File "/usr/local/lib/python3.8/site-packages/pandas/io/parsers.py", line 1891, in __init__
app_1    |     self._reader = parsers.TextReader(src, **kwds)
app_1    |   File "pandas/_libs/parsers.pyx", line 374, in pandas._libs.parsers.TextReader.__cinit__
app_1    |   File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
app_1    | FileNotFoundError: [Errno 2] File data/geolite_original.csv does not exist: 'data/geolite_original.csv'
```

**Comment by rmccarth** [comment]
fixed
